# Generated by Django 4.1 on 2023-04-30 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("Brand new", "Brand new"),
                            ("Like new", "Like new"),
                            ("Good", "Good"),
                            ("Fair", "Fair"),
                        ],
                        default="Good",
                        max_length=100,
                    ),
                ),
                ("message", models.TextField()),
                ("price", models.FloatField()),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="games.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"], "unique_together": {("user", "id")},},
        ),
    ]
